### PR TITLE
Follow links

### LINKED ISSUE #71: k6deps does not follow links in archives
Given an archive with the structure below, k6deps does not extract the `main.ts` file which is a link to the `data` file.
Processing the resulting temporary file with `k6pack` fails because this file is missing.

```
[ERROR] Could not resolve "../main.ts"

    ../../../../../../../tmp/k6deps-120020017/file/Users/nobody/code/atypical/pegasus/backend/test/k6/scenarios/commons.ts:2:25:
      2 │ import { BASE_URL } from "../main.ts";
        ╵                          ~~~~~~~~~~~~
```

## structure of archive file

```
-rw-r--r-- 0/0            3726 2025-02-25 18:16 metadata.json
-rw-r--r-- 0/0            4571 2025-02-25 18:16 data
drwxr-xr-x 0/0               0 2025-02-25 18:16 file
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical/pegasus
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical/pegasus/backend
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical/pegasus/backend/test
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical/pegasus/backend/test-data
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical/pegasus/backend/test-data/load-tests
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical/pegasus/backend/test/k6
drwxr-xr-x 0/0               0 2025-02-25 18:16 file/Users/nobody/code/atypical/pegasus/backend/test/k6/scenarios
-rw-r--r-- 0/0           39602 2025-02-21 17:04 file/Users/nobody/code/atypical/pegasus/backend/test-data/load-tests/user_tokens.json
-rw-r--r-- 0/0           14828 2025-02-25 18:15 file/Users/nobody/code/atypical/pegasus/backend/test/k6/config-builder.ts
-rw-r--r-- 0/0            2176 2025-02-25 00:03 file/Users/nobody/code/atypical/pegasus/backend/test/k6/config.ts
h--------- 0/0               0 1970-01-01 01:00 file/Users/nobody/code/atypical/pegasus/backend/test/k6/main.ts link to data
-rw-r--r-- 0/0            4825 2025-02-19 00:45 file/Users/nobody/code/atypical/pegasus/backend/test/k6/scenarios/commons.ts
-rw-r--r-- 0/0            6315 2025-02-24 04:26 file/Users/nobody/code/atypical/pegasus/backend/test/k6/scenarios/practice.ts
-rw-r--r-- 0/0            5832 2025-02-24 04:26 file/Users/nobody/code/atypical/pegasus/backend/test/k6/scenarios/review.ts
-rw-r--r-- 0/0            2186 2025-02-24 04:26 file/Users/nobody/code/atypical/pegasus/backend/test/k6/users.ts
-rw-r--r-- 0/0            1542 2025-02-24 04:26 file/Users/nobody/code/atypical/pegasus/backend/test/k6/utils.ts
```

### PR DESCRIPTION
**Pull request by pablochacin**
Follow links when extracting the archive. 

Also, use the script file in the archive's metadata when creating the bundle using `k6pack` instead of hardcoding `data`.
This is now possible because that file is guaranteed to exist.

Fixes #71

### CODE REVIEW

File: archive.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ type archiveMetadata struct {
 	Env      map[string]string `json:"env"`
 }
 
-//nolint:forbidigo
+//nolint:forbidigo,gocognit
```
Comment (szkiba) [inline archive.go:63]: gocognit usually indicates that a refactor would be needed...

**Review by szkiba — CHANGES_REQUESTED** [review]
According to gocognit, the complexity should be reduced and a little refactoring should be done...

**Review by szkiba — APPROVED** [review]
LGTM
